spring.application.name=studentmanagement
# ==========================================
# SERVER CONFIGURATION
# ==========================================
server.port=9094


# ==========================================
# SQLITE DATABASE
# ==========================================
spring.datasource.url=jdbc:sqlite:studentmanagement.db
spring.datasource.driver-class-name=org.sqlite.JDBC


# ==========================================
# JPA / HIBERNATE
# ==========================================
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ==========================================
# JWT CONFIGURATION
# ==========================================
jwt.secret=VGhpc0lzQVN1cGVyU2VjdXJlSldUU2VjcmV0S2V5Rm9yU3R1ZGVudE1hbmFnZW1lbnQxMjM0NTY3ODkw
jwt.expiration=86400000


